type TLang = {
  [key: string]: string;
};

export const PLANGUAGES: TLang = {
  ada: '39',
  assembly: '15',
  bash: '38',
  'c#': '1',
  'c++ (gcc)': '7',
  'c++ (clang)': '27',
  'c (gcc)': '6',
  'c (clang)': '26',
  'c (vc)': '29',
  'client side': '36',
  clojure: '47',
  'common lisp': '18',
  d: '30',
  elixir: '41',
  erlang: '40',
  'f#': '3',
  fortran: '45',
  go: '20',
  haskell: '11',
  java: '4',
  javascript: '17',
  kotlin: '43',
  lua: '14',
  'node.js': '23',
  ocaml: '42',
  octave: '25',
  'objective-c': '10',
  oracle: '35',
  pascal: '9',
  perl: '13',
  php: '8',
  postgresql: '34',
  prolog: '19',
  python: '5',
  'python 3': '24',
  r: '31',
  rust: '46',
  ruby: '12',
  scala: '21',
  scheme: '22',
  'sql server': '16',
  swift: '37',
  tcl: '32',
  'visual basic': '2',
};
