let friendGreet = [
      "I hope your day be filled with countless moments of joy and surprises. Good morning!",
      "Good morning, dear friend. I hope your day starts with a big, bright smile.",
      "You people are the family that I chose, and I wish you all the best things in life. Have a lovely morning!",
      "Every morning brings you new hopes and new opportunities. Don’t miss any one of them while you’re sleeping. Good morning!",
      "Life seems so beautiful to me thanks to some wonderful people in my life. You are one of them, my friend. Good morning to you!",
      "Good morning, bestie. May this day and all your days ahead be as radiant as the sunlight.",
      "However dark the night might be, it always ends in the dawn. So, never lose hope and have a great morning!",
      "Good morning, dear. May this day come with all the love your heart can hold and bring you every success you desire. May each of your footsteps bring joy to the earth and yourself. I wish you a magical day and a wonderful life ahead.",
      "A morning spent without a friend like you is a morning wasted. Please wake up, my dear friend. We are surely going to have a great day today! Good morning!",
      "I hope you shine as brightly and beautifully as the light of dawn. Good morning, friend.",
      "Being surrounded by such wonderful friends is what makes waking up this special. Good morning to you all.",
      "I love every morning in my life because they always give me another chance to spend one more day with you. Good morning my friend!",
      "Wake up and give me a text because your text is like sugar to me in my morning coffee. Good morning to my dearest and loveliest friend!",
      "Just as sunlight makes the darkness go away, you people make my sadness disappear. Good morning, friends.",
      "Whether it is a bad morning or good, you can always make it better through your effort. May today be your day.",
      "From the moment you open your eyes in the morning to the moment you close them at night, may each second in between pass with joy and laughter. You are a wonderful human being, making the world a better place. So, I hope that you find only the best things in it. Good morning.",
      "I’m shivering in the cold on this chilly morning, and all I want now is a hug from my best friend. So please wake up and send me a hug. Good morning!",
      "Enjoy the miracles of this beautiful morning and let them fill your heart with joy!",
      "Don’t worry. This good morning text can wait until you’re done with sleeping.",
      "Don’t stress too much about your failures of yesterday. Earn your success today! Good Morning Friend!",
      "Open your eyes and see the miracles happening around you. Be thankful because God loves you! Have a great day!",
      "A beautiful morning is calling out to you to enjoy its extraordinary beauty. You just cannot miss this morning in any way. Good morning!",
      "Wish you a comforting morning and a peaceful day, all of which you deserve.",
      "Birds are singing sweet melodies, and a gentle breeze is blowing through the trees; what a perfect morning to wake you up. Good morning!",
      "I wake up early in the morning every day just for having a few extra minutes to think of you. Right now, I’m thinking of you, my friend. Good morning!",
      "This morning is so relaxing and beautiful that I really don’t want you to miss it in any way. So, wake up dear friend. A hearty good morning to you!",
      "Distance can never change our friendship. Wishing you a productive day ahead. Good Morning!",
      "Mornings come with a blank canvas. Paint it as you like and call it a day. Wake up now and start creating your perfect day. Good morning!",
      "Start your day with solid determination and great attitude. You’re going to have a good day today. Good morning my friend!",
      "You’ve got one more day to rise and shine. Say thank you to God because he has been kind to you!",
      "I’m so excited to start a new day with my new friend. Let’s make it a day to remember!",
      "Whenever I think of you, all my worries go away. Good morning my dear friend!",
      "Good morning my lovely friend. I wish you a truly blissful day ahead. I’m looking forward to spending another eventful day with you.",
      "Friendship is what makes life worth living. I want to thank you for being such a special friend of mine. Good morning to you!",
      "I feel the happiest when I’m around you. No one makes me feel so special in life like you do. Thank you for being a part of my life. Good morning!",
      "Having a friend like you is one of the greatest privileges in life. So, if you ever question your worth, know that there are many like me whose smiles are caused by you. Your existence is special, and I hope that this day reminds you of that. Good morning, dear.",
      "Without the sun people can’t imagine life on the planet but I can’t imagine my life without you, my friend. Good Morning.. Have a great day!",
      "Sleeping is peaceful, but having friends like you, makes staying awake happier than ever. Good morning, lifelines.",
      "I wanted to start this morning with a good thought. So, I started thinking about our friendship and decided to send you this text. Good morning dear!",
      "You may be a tiny little part of this universe, but you are one of the biggest parts of my world. To me, you are a star, shining bright and guiding me in the darkest of nights. So, know that you matter and take good care of yourself. Good morning, buddy.",
      "We are apart for so many years, but all our memories of friendship are still fresh in my mind. Good morning!",
      "You must be smiling right now because I can see the sun started shining so bright. Good morning beautiful!",
      "A friend like you is pretty hard to come by in life. I must consider myself lucky enough to have you. Good morning. Wish you an amazing day ahead!",
      "I have never had a friend like you in life. You have all the good qualities a perfect friend should have. Good morning to you my friend. You are truly awesome!",
      "A very good morning to very good friend. May your day fill your life with all the happiness of this world. Good Morning Buddy!",
      "This message may reach you late, but I want you to know that your thoughts never come late in my mind. Good morning!",
      "There cannot be a better start to the day than recollecting some loving memories, and so many of my memories have you in it. So today, I wanted to thank you for being this amazing person and a reliable friend. May you keep shining bright and have a lovely morning.",
      "I wish you could meet yourself; you’re such a delightful person to be around! Have a good morning and a great life.",
      "“Just one small positive thought in the morning can change your whole day.” – Dalai Lama",
      "“Give every day the chance to become the most beautiful day of your life.” – Mark Twain",
      "Another day, another opportunity to live and laugh! Make the best out of it, buddy. Wishing you a very good morning.",
      "Rise and shine; because the world wouldn’t have been so beautiful if you weren’t a part of it!",
      "Don’t bother over yesterday and don’t worry about tomorrow, just enjoy this lovely morning. Wishing you a good morning.",
      "I hope you wake up with a body full of energy and a mind full of positivity. Good morning.",
      "“The day will be what you make it, so rise, like the sun, and burn.” – William C. Hannan",
      "For a true friendship there are four important word. Love, truth, honesty, and respect. Without these words friends are nothing. Good Morning. Have a wonderful day and enjoy the day.",
      "The more you count yourself as blessed, the more blessed you will be. Thank God for this beautiful morning and let friendship and love prevail this morning.",
      "“Think about the dreams you had last night to make your lazy morning a beautiful one.” – Lisa Lieberman-Wang",
      "“Good Morning — this is not just a greeting. It signifies a hope that the beautiful morning will bring a smile on your face and happiness in your life.” – Lisa Lieberman-Wang",
      "A new day has come. It’s your time to rise and shine like a star!",
      "Nothing else matters except the fact that you’re alive and ready to give a shot at success. Good morning!",
      "Wake up and absorb all the positive energy that morning gives you. Success will be yours today!",
      "My dear friends, I am wishing you a great and beautiful morning with joy. This morning, I want to say that always remember your past can’t alter and your future just doesn’t deserve the punishment.",
      "Wake up and sip a cup of loving friendship. Eat your heart out from a plate of hope. To top it up, a fork full of kindness and love. Enough for a happy good morning!",
      "Having morning coffee..watching the sunrise in the morning brings me a lot of happiness but there is a lack of a little thing; you are not here with me. Good Morning friend!",
      "As you read these words, know that right at this moment there is someone who is thinking of you and cares about you. Good morning!",
      "Woke up and now wondering how blessed I am to have you as my friends! Good morning, favorite people.",
      "Every single morning is a message from God that you’re still alive because you’ve to serve God’s purpose.",
      "Thank you for deciding to be my friend. Welcome to my world, and of course, welcome to a new day!",
      "Morning wind today is refreshing, and nature looks so beautiful outside. I was thinking of spending this day with a beautiful friend like you!",
      "It is easy to imagine the world coming to an end. But it isn’t easy to imagine spending a day without my friends. Good morning.",
      "Night has gone taking the darkness away from you. Now the sun is brightening your day to wake up and accept the opportunities given by the sun. Good Morning Buddy!",
      "My best friend deserves every wonderful thing in the world, and I hope you get those. Good morning!",
      "Having a best friend like you makes all the worldly worries go away. Wishing you a worry-free day too!",
      "Morning is the perfect time for counting blessings, and you’re the biggest blessing of all! Good morning, dear.",
      "I hope this good morning text will make you feel good right at the beginning of your day. Good morning dear best friend!",
      "Time for my best friend to wake up and do something special, just as he does every day. Good morning!",
      "It is a great feeling to start a morning with gratitude. So I am going to start my day by thanking you for being a good friend. Good morning.",
      "Romantic relationships are based on expectations and responsibilities. Professional relationships are based on gains and losses. But friendship is based on smiles and laughter. Good morning my friend.",
      "You make the world a better place simply by existing in it. So rise and shine, brighter than the light of day!",
      "No matter how busy our lives could be, I want you to know, that I still remember you. Good morning to the greatest person in my life, my friend!",
      "I cannot guarantee that you will have an awesome day but I can guarantee that you will be in the loving company of friends like me. Good morning buddy.",
      "This very start of the day, be happy for the breath of fresh air. Be thankful for the goodness that surrounds you. Most of all thank God for this beautiful friendship that you and I share. Good Morning!",
      "You are all my awesome friends because I think you are sweet and you think I am sweet, you think I am smart then I think you are saying right. Good Morning.",
      "You’re my best friend, and I hope for you to have only the best things in life. Good morning!",
      "Good morning, best friend. I just wanted to remind you that you’ll always find me beside you.",
      "If I’m coffee, then you are the sugar to it. If I’m bread, then you are the butter to it. What I’m trying to say is, that we are the best of friends and we make the greatest team! Thank you for being in my life. Have a sweet morning!",
      "You are one of the most beautiful souls that I know, and you deserve the loveliest things that the world has to offer. May love and light pave your way, today and every day. Wish you a peaceful morning. Rise and shine!",
      "The sunshine of this morning reminded me of you since you can shine just as brightly in your life! So, start your day with an optimistic mind, and conquer every obstacle that comes your way. I believe in you, my friend. Good morning and good day!",
      "No matter how many words I write, it would never be enough to express what an amazing friend you are! So, I want to start my day by sending you positive vibes instead. May today be your day and take you close to your dreams! Have a great morning.",
      "May you laugh till your stomach hurts. May you have confidence in your mind. May all the health and wealth be yours. May you get all the joy and success that you deserve. These are my wishes to you on this beautiful morning. Have a great day ahead!",
      "Our days on earth are limited, and so are our opportunities to live. Now that you’ve been gifted with another beautiful day live it to the fullest. Breathe and let go of your worries. Put yourself first and work on your dreams. Have a good morning and a great day.",
      "You are an incredible woman, and the world wouldn’t be the same without you. Remember this and have a sweet morning!",
      "May today have all the blessings in store for you. Have an amazing morning, girl.",
      "Good morning cutie pie! I hope your day ahead is filled with love, laughter and all the kindness that your heart can hold.",
      "Good morning, girl! May your day ahead be as lively, sweet, cute, beautiful, and amazing as you are.",
      "Wishing a lovely morning to my beautiful friend. May every step take you towards success and happiness.",
      "May heaven pour all its blessings upon you, and may the sun get jealous of how bright you shine. Wishing you a beautiful morning!",
      "Good morning, buddy. No matter how far away you are, you are always close to my heart.",
      "Good morning to my friend who lives far away from me. Hoping to meet you and catch up soon!",
      "Good morning, my friend. I miss you and all the fun that we used to have together. Hope you are staying well!",
      "You may be far away, but my good wishes will always find you. Have a blissful morning!",
      "I’m starting my day by thinking of you and our memories together. Wishing you a sweet and peaceful morning.",
      "The morning breeze will carry my love and morning wishes to you. Good morning and good day, friend!",
      "Life is short and days are even shorter. Sleep a bit longer and the day is over. Just kidding! Wake up and live the day. Good morning!",
      "Best thing about waking up late is that the thoughts of stress come to you late.",
      "Good morning, friend. Please don’t waste your time lying on the bed; get out of bed and find new ways to do it!",
      "You’re like the morning coffee. It’s not a great habit, but I don’t know how to get rid of it either!",
      "I have officially been diagnosed with the lazy virus, which you surely transmitted! Anyway, good morning, sloth!",
      "A friend like you can really spice up life like a grilled chicken; it looks good on the outside and tastes even better on the inside. Good morning!",
      "I dreamed of hitting you with a chair, then I woke up. Why do good dreams ever end?",
      "Good morning. Here’s to starting a new day with everything old.",
      "I know it’s hard to wake up every morning knowing that you’re still ugly and stupid. But we still have to wake up and live another day. Good morning!",
      "If you want to have a good time with your secret girlfriend, first get rid of your yelling wife. The same goes for your bed and alarm clock. Good morning!",
      "“Today I’m going to work hard and work intelligent” – that’s the joke I tell myself to bring a smile to my face when I wake up. Good morning!",
      "If you want to keep your dreams alive, sleep well and sleep tight. Better yet, never wake up in life. Just kidding! Good morning my friend!",
      "Dreamers like you don’t need inspirational good morning messages. They need big alarm bells and annoying friends like me. Good morning, time to wake up."
  ]



  let GN =[
      "Good night, I hope only sweet dreams find you at night.",
      "Good Night! Sending you my warm hugs and blessings.",
      "I hope God blesses you with many more peaceful nights. Good night, dear.",
      "When your day gets tough, remember that tomorrow is a fresh day after your sleep. Good night.",
      "Good night, my sweetheart. I hope the stars in the night sky lead you to lovely and sweet dreams tonight. Sleep well.",
      "Good night, my one and only. I wish I could hold you in my arms right now as I go to sleep.",
      "May the stars and moonlight shine brightly on your night. Have a good night.",
      "Before going to bed, thank God for another day to live and a good night’s sleep. Good night. May God bless you.",
      "Good night, love. You are my most precious treasure.",
      "Every night before I go to bed, I thank God for gifting me with you. Good night, baby.",
      "Have a good night, friend. May you have a restful and pleasant night’s sleep tonight.",
      "No matter how bad the day was, always try to end it with positive thoughts. Try to focus on the next day and hope for a sweet dream. Good night.",
      "No need to be upset or feel lonely tonight. Feel the calmness of this night with all your heart. Relax and have a tight sleep. Good night.",
      "You are my love, life, and redemption. Good night darling. I hope you have a lot of sweet dreams tonight!",
      "You have so many reasons to thank God, but first thank him for such a peaceful night like this. What a blissful night for a good sleep. Good night!",
      "May you have a sound sleep and wake up tomorrow with new hopes and positive energy. Good night to you!",
      "I don’t need anything else to warm me up as long as you love me. Because the warmth of your love is all I need. Good night!",
      "Wishing you good night and rest well, dear friend. Stop worrying about life. I will always have your back no matter what.",
      "May tomorrow be sunny and full of joy. Good night!",
      "As the moonlight dims and the world quiets, give yourself some rest. Here’s to hoping that your sleep is as sweet as you are.",
      "Do you know when an ordinary dream becomes a sweet dream? When someone as sweet as you is present in it. Good night! Please come and make my dreams sweeter!",
      "Put your worries aside and let your body feel the softness of your bed and the warmth of your blanket. May you have a peaceful sleep tonight!",
      "Good night dear. Tomorrow, you are going to have a great day. Just make sure your body is prepared to take on the challenges of tomorrow. Sleep well!",
      "Nights like this, are blessings from God. Don’t waste this blessing by staying awake. Good night to you. Have a sound sleep tonight!",
      "A new morning is waiting for you. Sleep well and sleep tight. Because the new day wants you to be fit and all charged up. Good night!",
      "Nights are for resting, not for worrying. So, get in the bed and get some sleep. Good night! A new day full of new possibilities awaits you.",
      "Let the fairies make your sleep wonderful. Good night.",
      "Yes, the night is very dark and silent. But it’s the perfect time to reflect on your day. Have a tight sleep and good night.",
      "The night has come to help you get rid of all the stress and pressure you had all day long. Get as much rest as you can get before starting another stressful day. Good night.",
      "I wish you have the sweetest dream of your life tonight. Goodnight.",
      "As the darkness of night follows, may you comfort and rest well. Sending you warm wishes and my love on your way. Sleep tight.",
      "I hope my good night text makes you smile and make it obvious that you matter. I hope you have a great day ahead, rest yourself well.",
      "Count all the sheep you can. When you finally doze off, I wish you have a nice dream to get rid of all the negative thoughts in your mind. Nighty night!",
      "May the angels keep you safe as you sleep. Good night my sweetheart.",
      "Good night, my love. I hope you have dreams about me at night.",
      "I hope that God fills your dark nights with the brightness of the stars and the moon. Have a good night my love.",
      "Every night before I go to sleep, I remind myself that I’ll have to love you more tomorrow than I have loved you today. Good night my love!",
      "I can’t think of anything more romantic and blissful than sleeping right beside you at night. I know someday, we will make it happen. Good night!",
      "Thank you for making my days warmer than usual. May the angels guard you while you have a great sleep. Good night, sleep tight.",
      "May your dreams be sweet and pleasant, my dear. I love you to the moon and back. Nighty night, my sweet prince charming.",
      "When I think about you, I forget about all my troubles in the world. I love you. Have a good night’s sleep, my sweetheart.",
      "Imagine I’m cuddling you while you’re sleeping. Good night, sweet dreams.",
      "Good night, the man of my dreams. While I’m sleeping, all I can think about is you.",
      "Let us both gaze at the same moon and admire that we live in the same timeline. Have a great night. Love you tons.",
      "I still can’t believe I have someone so charming like you in my life. Good night prince charming!",
      "I have had so many good moments today. I look forward to spending another eventful day with you tomorrow. Good night my dear!",
      "You are perfect with your every imperfection. Good night my love!",
      "Your thoughts keep me awake at night. But it doesn’t matter because I get to see your charming face when I’m awake. Good night!",
      "When I see you sleeping next to me in bed, I feel like the luckiest person to ever live in this world. Good night, sweetheart.",
      "I can’t wait for the day when we won’t have to say good night to each other by message. Until then, my darling, good night.",
      
      //friend
      "I hope you can let go of all your worries and have a pleasant sleep, my dear friend.",
      "I hope you have only positive thoughts in your dreams tonight, my best friend. Good night, sleep well.",
      "Don’t allow the stress and worry of the day to get to you. Relax and sleep. Good night, buddy.",
      "It’s the end of another spectacular day with you. Now recharge yourself because tomorrow we are going to have a bigger one. Good night dear friend!",
      "I don’t want to interrupt your much-needed sleep, but I really can’t close my eyes before I say goodnight to you. So good night friend!",
      "Boyfriends and girlfriends will come and go, but our friendship will forever radiantly glow. Good night friend.",
      "May all your troubles and concerns make their way out of your league and you have a good sleep ahead. Hugs, buddy! Night.",
      "I don’t want to disturb your sleep because I know you worked really hard all day, but I wanted to tell you that I am really proud of you. Good night, my best friend.",
      "I know you are exhausted but it’s a long night. So, you’ll have plenty of time to sleep and to dream. Good night my friend. Have a sound sleep!",
      "There are so many stars tonight and I wondered which one is you. Because my friend, you are a true star! Good night!",
      "Laughs, smiles, cries, frowns, fights and pranks – I’d have missed all of life’s best emotions if it weren’t for a bestie like you. Good night.",
      " I have the sweetest of dreams because I look forward to spending the next day with awesome friends like you. Good night.",
      "Just like how the skyline looks at night, our friendship adds a sense of character and glamour to my everyday life.",
      "I know I take you for granted every now and then even though you are my bestie, but being alone every night reminds me of how precious you are to me. xoxo",
      "Just like how the bright stars light up a dark night sky, the memories of our friendship are the twinkles in my life. Good night buddy.",
      "Even the melancholy of a dark and lonely night transforms into a sweet harmony when I think about the memories of our friendship. Good night.",
      "In life, success is not always measured by how big you can dream. Real success is often measured by the number of friends you can share your dreams with. Good night my friend.",
      "Good night, pal. Take a deep breath; no matter how difficult the day has been, you must always remain strong. tomorrow might be a better day.",
      "Every moment of these long nights is a moment to be thankful to God for having you. I am thinking of you and missing you a lot. Good night!",
      "The beautiful moon shining over my head is reminding me of a beautiful face. A face that can erase every painful memory in my life. I wish you good night with a tight sleep.",
      "No matter how hard the day was, take a deep breath and forget about it. A new beginning waits for you. Good Night, dear.",
      "Sweetheart, I hope you dream about me when you go to bed tonight. Good night.",
      "I hope you had a spectacular day today and now you’re looking forward to a good night’s sleep. May Almighty bless you, dear. Good night.",
      "I feel happy to have you in my life. Thank you for existing, dear. Have a lovely sleep ahead. Good Night, sleep tight.",
      "The last person I think of before falling asleep is you. You make everything at ease. Have a great sleep dear.",
      "My dreams are so full of you. I wish your dreams tonight be so full of me. I can’t wait for the morning to meet you and hug you. Good night!",
      "A million stars have lit up the night sky just like you have lit up my entire life. My days start with you in the morning and end with you at night! Good night!",
      "Kissing your forehead in the morning and at night before going to sleep has become my daily dose of happiness. Good night!",
      "The night breeze is blowing through my hair and the soft touch reminds me of your kisses. I wish I didn’t have to miss you this much.",
      "There is something that is big, warm, and fuzzy. Before you get too many ideas, you should know that it is a good night hug sent from me to you!",
      "I wish I was the pillow that pillow underneath your head tonight. I’d make sure you have the best sleep ever tonight. Good night!",
      "You are the reason why I have sleepless nights. You are the reason why I tend to hold my pillow tight. And you are the reason I can’t sleep without saying goodnight.",
      "When I go to bed, you’re the only thing in my thoughts and the only one in my dreams. Good night.",
      "Leave behind your worries and frustrations. As the sun rises once again at the dawn, wake up with new hopes, dreams, and determination.",
      "Good night. May the moonlight brighten your dreams and the dark clouds of the night cast a shade over all your concerns.",
      "Pack all of your sadness. It’s time to say goodbye to them. Take a break from all the negativity of life and get yourself a soft, warm bed to sleep on.",
      "Sometimes in life, you just have to wait for the right moment to start again. Just like at night you wait till the sunrise up and light up your way.",
      "Night is a good time to save your energy and boost your strength for the next day’s battle. So, don’t keep yourself up till late at night. Sleep early and sleep tight!",
      "It’s time to think about all the good things you did today. Take lessons from your mistakes and hope for a better tomorrow. Wishing you a good night!",
      "Always think positive thoughts before going to bed, no matter how difficult the day has been. Good night. Have a pleasant sleep.",
      "Learn from yesterday’s mistakes and use what you’ve learned for tomorrow. Have a good night.",
      "You owe it to yourself to end the day with good thoughts. Today, you got up and did what you could. Tomorrow is another fresh start no matter what.",
      "May the dark clouds of the night shadow all your worries. May the shining stars illuminate your dreams, and may the soft moon be a soothing balm to all the troubles in your life. Good night.",
      "Stop thinking about all the things people said to hurt your feelings. Just hold on tightly to the memories of all the times someone made you smile. Good night.",
      "The stars and moon arrive just to wish you a good night. Let the light of the moon guide your dreams as you pass the night away.",
      "Night is longer than a day for those who DREAM and the day is longer than night for those who make their DREAMS come true.",
      "“May tonight be a lovely and serene bridge that will lead you to a wonderful tomorrow.” – E. Joseph Cossman",
      "“Good night! God keep you till the morning, and guard you safe from every harm.” – Lyliam Williams",
      "“I like the night. Without the dark, we’d never see the stars.” – Stephenie Meyer",
      "“As the night gets dark, let your worries fade. sleep peacefully knowing you’ve done all you can do for today.” – Roald Dahl",
      "“The darker the night, the brighter the stars, The deeper the grief, the closer is God!” – Fyodor Dostoyevsky",
      "“I wish for you a good night of sleep, sweet dreams, and a smiling morning.” – Debasish Mridha",
      "“Throw off your worries when you throw off your clothes at night.” – Napoleon Bonaparte",
      "“I just want to say, good night, sweet prince, may flights of angels sing thee to thy rest.” – Harry Dean Stanton",
      "“The longest way must have its close – the gloomiest night will wear on to a morning.” – Harriet Beecher Stowe",
      "“Night is the wonderful opportunity to take rest, to forgive, to smile, to get ready for all the battles that you have to fight tomorrow.” – Allen Ginsberg",
      "“The best bridge between despair and hope is a good night’s sleep.” – E. Joseph Cossman",
      "“Night is always darker before the dawn and life is the same, the hard times will pass, every thing will get better and sun will shine brighter then ever.” – Ernest Hemingway",
      "“Go to sleep knowing that I loved you this day, and each tomorrow my love grows stronger. Good night!” – Catherine Pulsifer",
      "“Good night my dearest love and have pleasant dreams. Here’s to hope that tomorrow will be as sunny and bright as you are.” – Anthony T. Hincks",
      "“Good night. Let the stars light the way to where your dreams can be found awaiting your arrival.” – Anthony T. Hincks",


      "Feel the peace of the night with all of your heart. Relax and have a good night’s sleep.",
      "Good night. I hope your sleep refreshes and recharges you for the next day.",
      "God bless you with lovely dreams while you sleep tonight. Good night.",
      "Good night. I only think about you when I’m going to sleep.",
      "Have a good night. I hope your dreams are filled with stars and moonlight.",
      "Good night, buddy. If you ever need me, know that I am only a phone call away.",
      "You are more beautiful than any dream I’ve ever had. Have a good night.",
      "Good night to my favorite human being in the entire world.",
      "May all the worries disappear from your life. Good Night!",
      "I’m sending you my love while you sleep sweetly, love. Good night.",
  ]

  let familyGN = [
      "My family, may God bless you with lovely and beautiful dreams tonight.",
      "I wish you only wonderful days and peaceful nights, my family. Have a good night.",
      "Good night, mom. I hope your sleep offers you comfort and relieves you of your stress and frustration from the day.",
      "You earned rest after working so hard all day, dad. I hope you get a good night’s sleep.",
      "A beautiful day has just ended; let us hope for another good day tomorrow. Good night, mom, dad, and my siblings; I love you, my dear family.",
      "Good night dear sister! Sleep peacefully; the angels will keep you safe and sound as you sleep tonight.",
      "Good night my sweet brother! Take all your negativity when you go to bed, and start your new day with optimism.",
      "Good night my son/daughter! I pray and hope that God sends you only good dreams and no nightmares when you sleep tonight.",
      "I hope you dream about me, and if you don’t, I hope you have nightmares. Good night.",
      "The quietness of this beautiful night reminds me of you. How can I sleep peacefully at this night without disturbing you?",
      "Sleep is a kind of temporary death for us. How nice it would if some people never woke up in the morning! You know I’m talking about you! Good night!",
      "Even a bad person like you can do some favor to the rest of the world. All you have to do is have a tight sleep tonight and not wake up in the morning.",
      "Go to sleep before the bed bugs get real hungry again! Good night and sleep tight!",
      "Do you know that I’m missing you a lot right now? Can you please sleep early tonight so I can meet you in your dreams ASAP? Good night!",
      "Good people sleep better than bad people, so I guess you and I are not sleeping well tonight.",
      "Nights are good time to watch horror movies. Then going to bed knowing ghosts are unreal. But waking up at midnight with fear and sweat. I wish you a night full of all these experiences!",
      "Sometimes I am goofy, but don’t ever think that I don’t care. No matter what, for you, I will always be there. Good night.",
      "Send me a text if you can’t sleep and call me if you get nightmares. I will kick the living daylight of all your bad dreams. Good night.",
      "Hey, Night is made for rest not for text. So switch off your cell phone and go to the world of dreams. Good night.",
      "Night is to see the dreams and day is to make them true. So it’s good to sleep now and see the dreams. Good Night, Sweet Dreams!",
      "Guess what I saw in my dream last night? I saw you, and it was a terrifying nightmare.",
      "I know you’re sleeping, but please keep talking to me since I’m not sleepy yet."
  ]


  let herGN = [
      "Good night, the love of my life. You are my dream come true.",
      "Good night sweetheart. Tonight, as you sleep with all the silence in the world, just know that I’ll be in your dream to give you a hug!",
      "Someday, we’ll be right next to each other in the bed and we’ll be waiting for a new morning with a new passion to love each other! Good night!",
      "May all the stars guide you to a night of sound sleep as I fight every nightmare for you. Sending you my love while you have sweet dreams, love.",
      "The best part of the night is holding you in my arms and sleeping next to you. Good night. Have sweet dreams, my darling.",
      "Nothing gives me more pleasure than holding you tightly in my arms. I wish I was right beside you tonight to hug you. Good night!",
      "You are the woman of my dreams, the only one I want to see in my dreams every night. Have a good night.",
      "I hope in spite of having a rough day, you will have a relaxing and sound sleep. I love you more than you know, sweetie. Good night.",
      " I’m looking forward to meeting you in my dream, sweetheart. May you rest well. Have a good night and sleep tight. I love you so much.",
      "One day we will be saying good night to each other in person rather than via text message. Eagerly waiting for that day. Have a cozy and warm night. I love you a lot. ",
      "Tonight, I’ll be your most colorful dream and your sweetest sleep in life. Just let me in when I knock on the door of your heart. Good night!",
      "I spend my days thinking of you and my nights dreaming of you. You are everything in my life. I want nothing more and nothing less! Good night!",
      "Tonight, the cold of the night can’t touch you, Because the warmth of my love will keep you warm for the whole night. Good night!",
      "Every second of these long hours of the night, I look up at the sky and thank God for allowing me to love you. Good night, baby.",
      "You are the first thing that comes to mind every night when I stay up late thinking about all the things I am grateful for. Good night.",
      "Good night, my love. I hope the good night’s sleep washes away all your concerns, stress, frustration, and disappointments from the day.",
      "Good night, the woman of my dreams. I feel very blessed and honored to be the one who is able to love you and have you love me back.",
  ]


  let GE = [
      [
            "Good Evening! Wish you an evening filled with love and warmth.",
            "Good Evening! I hope you had a good and productive day.",
            "Good evening to the love of my life. Thank you for making each of my moments beautiful.",
            "Good Evening! No matter how bad your day has been, the beauty of the setting sun will make everything serene.",
            "May all your worries set with the sun, and may a calm and peaceful night await you. Have a good evening!",
            "May the serenity of this beautiful evening touch your soul and put your mind at ease. Wish you a lovely evening!",
            "No matter how busy I stay, you are always on my mind. Have a wonderful evening, love.",
            "Wishing you a great evening and a wonderful life to you, my dear friend. Never forget how special you are!",
            "May the setting sun take down all your sufferings with it and make you hopeful for a new day. Good evening!",
            "Thank you for making my days beautiful and evenings full of joy. You are the reason behind all my smiles and laughs. Wishing you a good evening.",
            "It doesn’t matter how hectic your day was, you can’t help admiring the beauty of this evening. I hope you are having a good time right now! Good evening!",
            "Good evening dear. Thank you for making my evenings so beautiful and full of love.",
            "Whether your day was good or bad, it has come to an end. Good evening and good luck for tomorrow.",
            "Evening is a good time to look back at your day and think about everything you have done. Enjoy your evening with positive thoughts.",
            "I wish you an amazing evening full of gossip and coffee. Just know that you are always in my mind. Enjoy this evening to the fullest!",
            "It doesn’t matter where I am and what I do, you will always be in my mind and in my heart. I am missing you a lot at this evening!",
            "Happiness can’t be behind sorrow, It is your choice to make a better tomorrow, Enjoy this beautiful day with a lovely smile, Good evening!",
            "Evenings are your chance to forget the mistakes you made during the day, so you can have the way for the sweetest of dreams. Good evening!",
            "Evening is a good time to look back at the day and think about all the good things you have done. I wish you an evening so full of satisfaction and inspiration.",
            "Good evening my friend, take a sip of your coffee and forget the troubles of the day.",
            "If I have another life to live, I’d still choose another lifetime with you. I can only find real joy and happiness in your arms. I love you. Good evening.",
            "Evenings are just like you, full of colors and new hopes. I wish you a good evening my love.",
            "It’s a perfect time to get rid of your worries and make yourself prepared for what’s coming tomorrow. Make this evening the beginning of a wonderful journey.",
            "Evenings are for relaxing with a cup of tea and preparing yourself for tomorrow. Good evening buddy!",
            "The sun sets every evening with a promise to rise once again at dawn. Evenings are so full of hope and inspiration. Wishing you a very wonderful evening!",
            "I hope you are having a refreshing evening as I am having here thinking of you. Good evening, my love.",
            "Sometimes, the best thing you can do is not think, wonder, imagine, and not obsess. Just breathe and have faith that everything will work out for the best. Good evening!",
            "I want to see all the beautiful sunsets of my life only with you my love. Good evening!",
            "As you look at the setting sun, forget everything that’s bothering you. Good evening!",
            "Friends like you are the reason why there’s never a sunset in my life’s happiness. Good evening.",
            "Good evening my dear friend. No matter how hard your day was, stay optimistic and start afresh tomorrow.",
            "I know today was hard for you but I also know that tomorrow will come with new hopes and aspirations. Good evening my friend, keep fighting.",
            "Evenings are simply the blessings of looking at your mistakes and working on them. Never miss your chance to overview your day with your evening tea. Good evening bestie!",
            "Hope you relax your day with a fine cup of coffee and have a blessed evening enjoying the beauty of nature. Have a great evening, friend.",
            "Dear friend, enjoy this beautiful evening with a cup of tea and forget about your tiredness and loneliness.",
            "If you are seeing this message you are an idiot because only an idiot can ignore the beauty of this evening by checking random messages on his cell phone!",
            "Good evening my friend. We haven’t met for so many days. Let’s meet in this beautiful evening and catch up on things.",
            "Have a look at the horizon where the sun sets and make a promise to yourself that you’ll do better tomorrow. Wishing you a very good evening.",
            "Evening welcomes darkness into this world. And the one that welcomes darkness also welcomes the ghosts. I wish you an evening full of ghostly experiences!",
            "You know the time when you start to feel a bit sleepy, but you can’t go to bed because mommy says its time to study. Guess what, It’s a good evening dear friend!",
            "The sun sets in the evening today with the promise that it will rise again tomorrow. Here’s hoping that this awesome day comes to a close with the promise that there will be better tomorrow. Good evening.",
            "Wish you some good snacks and nonstop laughter on this lovely evening.",
            "Here is my wish for you to have a great evening, Have a cup of coffee, relax and finish off the day’s work, Good evening and have a great time!",
            "There’s no need to add sugar to your evening coffee because you’ve just been poked by a sweet person like me. Good evening friend.",
            "Your character does not depend on your situation in life, It all depends on your will and spirit to succeed in life, So stay in bliss, Good evening!",
            "I hope our friendship always remains as beautiful and breathtaking as a picturesque sunset. Good evening.",
            "I wish you have a good evening; spending more time with yourself and find out what do you really want to do! Evenings are pure blessings.",
            "As the sun sets in the evening, it actually gives you another chance to be bold and fierce. Take your chances and renovate yourself for the new day.",
            "Evenings are comforting because they mark the endings of our hectic days. So, enjoy the darkness before life gets busy again.",
            " It Doesn’t matter whether you are spending the evening at home or going outside, I just hope that you’re having a good time!",
            "You are my sunshine, moonlight, and everything in between. Hope you have a delightful evening, sweetie.",
            "Good evening, my love. I just wanted you to know that I have thought about you the whole day long, and even now I’m thinking about you only.",
            "As I look at today’s setting sun, the only thing I can think of is you. Good evening my love.",
            "I miss you every time I’m away from you. I just wanted you to know that. Good evening, love of my life.",
            "The most precious place in the world is in your heart, keep me there and don’t let me go. I love you and without you, the life means nothing to me. Good evening.",
            "May today’s evening help you to calm your mind and forget all your problems. I will always be there to support you and cheer you up. Good evening darling.",
            "My evenings are incomplete without you. Every single sunset seems beautiful because of you. Thank you for coming to my life and making it so beautiful. Good evening my love.",
            "Love cannot be measured by the times we spend together but by the minutes we spend thinking of each other. One more evening of my life spent thinking about you!",
            "When I’m awake, you are in my mind. And when I’m asleep, you are in my dream. You are everywhere and anywhere in my life. Good evening beautiful!",
            "You are the home to me, and there’s no place I’d rather go to than in your arms. Good evening and I love you.",
            "I don’t know of any beautiful smile without yours. I have never seen more beautiful eyes than yours. And I have never known anything more comforting than an evening hug from you!",
            "Life is easy with you and I need your support to convert my sadness to smile, my loss to win and my bad to good. Only you can drive out the entire negative thing and make my life wonderful. Good evening.",
            "Each time I gaze at a star, I think of you. Like a star, you seem so near yet so far. But in my heart is where you truly are. Even if we’re oceans apart. Good evening!",
            "I love you beyond anything else in the world. It is true, the path of life is not easy, but we together make it beautiful. Good evening sweetheart.",
            "The gentleness of this evening breeze makes me miss you more and more. You’ll always have a place in my mind and heart. Good evening!",
            "The canvas of my life is perfect as you add all colors in it; the smile, joy, happiness, and the love of life. I want to be with you always in your heart to share my life and to care for you. I wish you a very good evening.",
            "Do you know what parties, romantic dates, fun night outs, beautiful sunsets and candlelit dinners have in common? They all begin in the evening. Have a good one!",
            "The beauty of the setting sun reminds me of our love, it’s just so pure and divine! I hope you have a great evening, honey.",
            "You and a mug of coffee are the best combinations of my evening fantasy. I can’t wait to make this one true so soon. Wishing you a good evening dear!",
            




            "“The evening of a well-spent life brings its lamps with it.” – Joseph Joubert",
            "“The evening’s the best part of the day. You’ve done your day’s work. Now you can put your feet up and enjoy it.” – Kazuo Ishiguro",
            "“May the Love of the Lord be with you, #GoodEvening”",
            "“Loving yourself isn’t vanity. It’s sanity! #GoodEvening”",
            "“Come in the evening, or come in the morning; Come when you’re looked for, or come without warning.” – Thomas Osborne Davis",
            "“Evenings are the beautiful sweet spot between the harsh light of the day and the dead darkness of the night.” – Unknown",
            "“The evening sings in a voice of amber, the dawn is surely coming.” – Al Stewart",
            "“Sending my prayers to you this evening. May God keeps you and secure thoughout the night.”",
            "“Good Evening! There is no such thing as a perfect person, but someone’s heart can have a perfect intention.”",
            "“May your love for me be like the scent of the evening sea drifting in through a quiet window so I do not have to run or chase or fall … to feel you all I have to do is breathe.” – Sanober Khan",
            "“It’s not what we have in life, but who we have in our life that matters #GoodEvening”",
            "“You were born to be real, not to be perfect. #goodevening ❤️”",
            "“Evening is not the time to lock ourselves in the house but its the time to escape from a materialist world’s prison.” – Red White Love",
            "“What is love? It is the morning and the evening star.” – Sinclair Lewis",
            "“O, thou art fairer than the evening air Clad in the beauty of a thousand stars.” – Christopher Marlowe",
            "“Inhale and hold the evening in your lungs.” – Sebastian Faulks",
            "“When the evening shadows and the stars appear and there is no one there to dry your tears. I could hold you for a million years. To make you feel my love.” – Adele",
            "“Be thou the rainbow in the storms of life. The evening beam that smiles the clouds away, and tints tomorrow with prophetic ray.” – Lord Byron",
            "“Everybody wants happiness, and nobody wants pain, but you can’t have a rainbow without a little rain! Good Evening”",
            "“Beauty attracts the eyes but personality captures the heart! Good evening ❤️”",
            "“Inhale and hold the evening in your lungs.” – Sebastian Faulks",
            "“Each morning sees some task begun, each evening sees it close; Something attempted, something done, has earned a night’s repose.” – Henry Wadsworth Longfellow",
            "“With an evening coat and a white tie, anybody, even a stockbroker, can gain a reputation for being civilized.” – Oscar Wilde",
            "“The lights begin to twinkle from the rocks: The long day wanes: the slow moon climbs: the deep Moans round with many voices.” – Lord Alfred Tennyson",
            "“Sweet the coming on of grateful evening mild; then silent night With this her solemn bird and this fair moon, And these the gems of heaven, her starry train.” – John Milton",
            "Evening is the time for peace, to gather up the shattered mind and have a tremendous time. I hope you are enjoying your evening.",
            "My feelings for you cannot be expressed with any words possible but the way evening adds a new chapter in our day – I will always be there to cheer you up. Have a good evening.",
            "All the cool breeze the evening brings may take away all your worries and gift you a blessed time. Have a good evening.",
            "Stay happy and try to enjoy every bit that life offers you. Don’t forget to smile and put your heart at ease. Have a great evening, my dear.",
            "Good evening brother! Hope you had a day full of laughter and productivity! Now enjoy your evening.",
            "Good evening dear sister! Forget the sorrows of your day, cherish the good things and make the most out of this beautiful evening!",
            "May this beautiful sun makes you glow 5 times on your evening selfies. Have a blessed evening with having your kind of fun.",
            "I just wish that you have a fun evening and forget your stress. You are a great mind with lots of possibilities. Never let the evil world get you! Enjoy your evening.",
            "In this lovely evening, I remember you and all the beautiful moments we had the chance to share. You are my MVP! Have a great evening.",
            "I love how the evening works as a pause button and puts every hectic day on avoiding for a while. I hope you are enjoying your paused moment. Thank you for always having my back.",
            "I think evenings are the coolest time of the day as it lets you reflect on your whole day. Hope you work on it and have a great time.",
            "Stop stressing about your sore day and enjoy the cool breeze of the fascinating evening. Eat lots of good food and cherish your evening well. Have a great time, dear.",
            "Follow the rhythm of your heart, Heart takes you to the destination, Where your goodness dwells, Have a happy evening!",
            "The sun will rise and set. The stars will appear and disappear. The clouds will gather and later wither… nothing can stop nature’s cycle, just like nothing can stop you from succeeding. Good evening."
        ]
  ]


  let herGE = [      
      "I want to be with you now, always and forever. Good evening my sweetheart.",
      "Evenings are always full of motivations and a new chance to look forward to the good times. So, never waste it darling. Have a warm evening. I love you so much.",
      "Even if I have another life to live, I would spend all my time with you without any doubt. I love you more than you can imagine, babe. Have a great evening.",
      "Stop worrying about the hectic day and take your time out. Enjoy everything around you and make sure to have a serene evening, my love.",
      "Good evening my lovely wife. You are the most precious thing to me and I hope you keep smiling.",
      "Good evening to the most gorgeous woman I have ever known, who, luckily, is all mine!",
      "Wishing a warm and lovely evening to my princess. You deserve every good thing in life!",
      "May this evening bring lots of positivity and motivation to you, baby. May every sorrow fade away from your life, and many beautiful miracles await you because you deserve it all. Have a good time, my queen.",
      "May this beautiful evening refresh your body, soul and mind. I love you beyond words. Good evening, princess.",
      "You are more beautiful than the lights of sunset. As you look at the beautiful sun forget all your stress and greet your evening with a big smile. Good evening sweetheart!",
      "Today’s sunset is so beautiful. I wish you were here to see it with me and we could have our lovely evening chats with a cup of coffee. Good evening my beautiful girlfriend. Can’t wait to meet you again.",
      "The thought of seeing you again makes my evening full of joy. See you soon sweetheart.",
      "On this beautiful evening, I am remembering all the beautiful evenings we had together. I miss how we used to have our evening teas together. Good evening love.",
      "Evenings are like the lamp that lights up our day and makes it better. Never lose hope and enjoy it with every possible bit. I love you, baby. Have a  good evening.",
      "I wish you enjoy your evening with joy, laughter and peace at your heart because my love these are the things that you truly deserve. I love you so much, have a great time.",
      "You make my world brighter with your sweet smile, babe. I hope you are having a good evening. And know that spending my evening thinking about you is nothing but an absolute pleasure.",
      "Counting days till I can come home to you every evening for the rest of my life. Have a good evening, baby.",
      "Your eyes are as beautiful as the evening sky, and I could never get enough of staring into it. Have a soothing time, love.",
      "I never knew love is such a beautiful feeling until I met you. You are my angel on earth, and I love every bit of you. Hoping to spend each of my days with you, darling, and wish you a pleasant evening.",

  ]


  let himGE = [
      "Good evening my love. You don’t know how lucky I am to have you in my life. I wish I could spend all the evenings of my life sitting beside you looking at the setting sun.",
      "You fill my heart with peace and there’s no ending to my love for you. Wishing you a good evening, sweetheart.",
      "Don’t take too much pressure on yourself. Breathe out and relax. Look at the brighter side and forget the bad moments. Have a good evening, my love.",
      "Evening becomes special without a company and you are my best companion, my love. Evenings, where I get to spend my time with you, are pure blessings.",
      "The world becomes beautiful when I am with you. You make me feel worthy and loved. I wish you get rid of your worries and have all the happiness of this world. Good evening love.",
      "Good evening, my love. I appreciate everything you do for me and our relationship. I’m proud of the man you are, and I hope you have a lovely time, now and always.",
      "On this beautiful evening, I wanted to thank you for turning my life into this heavenly dream. I love you.",
      "Good evening, my king. Know that I love you with all my heart.",
      "I dream of many cozy evenings of me being tightly wrapped in your arms. Hugs and kisses to you, sweetie.",
      "After a long and hectic day, the evening is the time when you can take a break. I want you to make a cup of tea and forget your stress. Good evening honey.",
      "Dear love, I wish you a very good evening. Though I am not with you today, my love and support will always be with you. Love you.",
      " I hope you will enjoy this beautiful evening in the sweetest serenity. Good evening, my dearest. I love you dearly.",
      "Every day when the sun sets out it actually promises for a new beginning and gives you an opportunity to steal the show. Take it and make the world glow! Have a great evening.",
      "Evenings are warm and make you feel special in their own ways. Never miss a chance to enjoy your evening no matter how busy you are.",
      "It doesn’t matter how tough your day was, I wish you have a relaxing evening and take some time out for yourself. Don’t stress out too much, I love you anyway. Have a good evening.",
      "Forget about the day’s toil and make new moments and enjoy them to your fullest. I hope you have a great evening, babe. I love you.",
      "You are the cutest person I know and the best person I know. Good evening my love :*",
      "I am not afraid of the dark because I know you’ll be guiding me through it. Sending love to you on this serene evening, darling.",
      "I start thinking about you each day. I stare at your pictures on my lonely afternoons. I crave your company in the evenings, and I dream of you at night. You are never off of my mind, my man. May your evening go beautifully.",
  ]




  let GF = [
      "I could fight with the whole world just to see your smiling face.",
      "I love how you keep on taking my breath away every single time. I love you so much, honey.",
      "I have tried to stop thinking about you, but I couldn’t. Your thoughts are inseparable and impossible to remove from my head.",
      "The most beautiful feeling on earth is waking up with a smile on my face and realizing it was you in my dreams the whole night.",
      "You are stunningly beautiful and elegant in all the ways possible.  I’m spell bounded with your beauty.",
      "Words don’t have the power to express the feelings within my heart. I’m in love with you with every inch of my body!",
      "Your gentle touch and sweet smile make me fall in love with you again and again. I want my forever to be spent with you!",
      "If I had to climb a thousand mountains to see you, I would do that without thinking twice. You’re the very essence of my life!",
      "You know, you’ve been living in my heart for way too long. It’s time to start paying rent.",
      "You dwell in every inch under my skin. Your thoughts constitute my mind. Without you, I’m nothing but a stupid, mindless organism on earth.",
      "The sunshine seems a little brighter and a bit warmer since you are in my life. By no means can I deny the blessings of your presence in my life!",
      "Whenever I look at you, my heart gets caught in a hitch. You’re the most gorgeous woman in my eyes!",
      "My love, I’m terrified of losing you more than anything else in the world.",
      "You fill my life with excitement and my mind with peace, and I couldn’t love you more!",
      "Congratulations! You have won my heart without any struggle. Hope you want to celebrate it with a nice romantic dinner soon.",
      "Stop thinking about me, because I am getting way too many hiccups. Kidding never stops, okay?",
      "I wish I could be your mirror. I envy it. It can see you every now and then and here I am; thirsty for only one glimpse of yours. Bless me with your glimpse prettiness.",
      "You are the kindest soul who makes my life beautiful and loved.",
      "You’re the girl I want to go to after every good and bad day. You are my home and my peace. I hope we stay together till the end of time.",
      "You gave meaning to my purposeless life, and I can never thank you enough for that, sweetheart!",
      "You own a piece of my body, which I call my heart. Without it, I can’t live for a single moment!",
      "The biggest reward of my devotion towards finding a soulmate in life is you. Now I can’t live without you!",
      "All the dreams I had about life came true in the form of you. I am forever grateful for having you in my life.",
      "Happiness to me was just another word out of the dictionary. But then you came into my life and gave meaning to that word.",
      "Our thoughts connect so perfectly with each other that sometimes I think we are truly made for each other!",
      "I crave for you on a stormy day just as much as I crave you on a starry night. With you, every moment of my life is blissful!",
      "Your smile brightens my day like the first sunshine of the day. You are the one that holds the key to my heart!",
      "It doesn’t matter where you are; I can always hear your heartbeat when I lay down and see your face when I close my eyes. I love you, sweetheart!",
      "Such an amazing girl like you doesn’t come from this earth; they come straight from heaven. You’re the most amazing girlfriend ever!",
      "It’s you and always going to be you- get that and seal it to your heart, babe.",
      "Without you, my world is empty, and my life is emptier. I wish I had the words to describe how much I miss you all the time!",
      "Missing you is like a disease that I’ve been suffering from since I first met you. The only cure to this disease is your presence by my side!",
      "I’ve tried so hard to cope with the pain of not having you with me, but in the end, I’ve realized that it’s impossible to live without you. I miss you!",
      "My eyes are begging to me see you, and my soul is crying to be with you. I miss you so badly all the time!",
      "You’ve become a habit to me, so much so that if I don’t see you just for a single day, it feels like I’m locked up in an empty cell with no air to breathe.",
      "Life without you seems terrible, meaningless, and full of mistakes. I miss you so much!",
      "Only you can bring out the best in me. Without you, I don’t feel like myself anymore. I miss you so dearly!",
      "Distance can never affect our relationship. No matter how far you are from me, your thoughts are always on my mind.",
      "Today, you deserve every ounce of happiness in this world. Good morning to my sweetheart!",
      "Have an amazing day, and know that you are always in my thoughts. Good morning to you, babe!",
      "I am grateful to God for giving me one more day to love you, to care for you, and to make you feel extra special. Good morning!",
      "Good morning my love. Let the first ray of sun this morning kiss you on the forehead and remove all your worries.",
      "You hold the most special place in my heart. Without you, my day can not start. Wake up beautiful, good morning to you!",
      "A beautiful day is waiting outside for you. Open your dreamy eyes and experience the wonders of nature. Good morning to you!",
      "Wake up with a smile on your face because the sun has denied shining without seeing your beautiful smile in the morning!",
      "Waking up in the morning and realizing that you’re in my life makes everything extra special all day long. Good morning my love!",

      "I am desperately looking for a GPS because I’m so lost in the world of you.",
      "You shine so brightly all the time it makes me convinced that love is truly blind.",
      "I’d rather be breathing carbon dioxide than being alone without you in this life. You’re the fuel I need to live!",
      "I am Mr. Right and I heard that you are looking for me. Will you be my Miss Always Right?",
      "My love, having you in my life, every day feels like a holiday! So I cannot wait to marry you and have an eternal happy vacation!",
      "Workout burns calories for sure. But do you know what else burns calories too? Kissing!",
      "You always remind me of my old car. Always taking up a big chunk of space in my garage but ain’t going nowhere ever!",
      "I’ve always followed my heart, but with you, it was a bit different. I forgot to bring my brain along.",
      "If being stupid together is not love, then I don’t know what else is. Let’s continue being stupid together forever!",
      "You gave me two choices, either be the right one or be the happy one. I decided to be the second one."
  ]


  let GFNight = [
      "I want my dreams to be just as sweet and tender as your soft kisses on my forehead. Good night my love!",
      "A peaceful slumber is due, and a starry night is waiting outside for you. Let the magic of tonight wrap itself around you! Good night!",
      "May the comforting silence of night embrace you with a promise of peaceful slumber. Good night my love! May you sleep tight tonight!",
      "Surrender your body and soul to the night and let it recharge your soul with new energy and new hopes. Good night my love!",
      "Good night my princess! May the angels comfort you all night long with sweet lullabies from heaven!",
      "May the radiant moon of the night guide your soul to the land of dreams tonight. May you have a fresh start tomorrow. Good night!",
      "Close your eyes and surrender to the gift of the night. The vigilant moon up in the sky will keep you safe all night long. Good night dear!",
      "Close your eyes and listen to the air. Can you hear my prayers for you echoing in it? I’ve asked God to keep you safe tonight and return you safely to me tomorrow!",
  ]


  export {
      herGN,
      familyGN,
      GN,
      
      GE,
      herGE,
      himGE,

      GF,
      friendGreet,
  }