let motivation = [
      "Life isn’t about getting and having, it’s about giving and being.",
      "Whatever the mind of man can conceive and believe, it can achieve.",
      "Strive not to be a success, but rather to be of value.",
      "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.",
      "I attribute my success to this: I never gave or took any excuse.",
      "You miss 100% of the shots you don’t take.",
      "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.",
      "The most difficult thing is the decision to act, the rest is merely tenacity.",
      "Every strike brings me closer to the next home run.",
      "Definiteness of purpose is the starting point of all achievement.",
      "We must balance conspicuous consumption with conscious capitalism.",
      "Life is what happens to you while you’re busy making other plans.",
      "We become what we think about.",
      "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover.",
      "Life is 10% what happens to me and 90% of how I react to it.",
      "The most common way people give up their power is by thinking they don’t have any.",
      "The mind is everything. What you think you become.",
      "The best time to plant a tree was 20 years ago. The second best time is now.",
      "An unexamined life is not worth living.",
      "Eighty percent of success is showing up.",
      "Your time is limited, so don’t waste it living someone else’s life.",
      "Winning isn’t everything, but wanting to win is.",
      "I am not a product of my circumstances. I am a product of my decisions.",
      "Every child is an artist.  The problem is how to remain an artist once he grows up.",
      "You can never cross the ocean until you have the courage to lose sight of the shore.",
      "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
      "Either you run the day, or the day runs you.",
      "Whether you think you can or you think you can’t, you’re right.",
      "The two most important days in your life are the day you are born and the day you find out why.",
      "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.",
      "The best revenge is massive success.",
      "People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily.",
      "Life shrinks or expands in proportion to one’s courage.",
      "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.",
      "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
      "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.",
      "The only person you are destined to become is the person you decide to be.",
      "Go confidently in the direction of your dreams.  Live the life you have imagined.",
      "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.",
      "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.",
      "Certain things catch your eye, but pursue only those that capture the heart.",
      "Believe you can and you’re halfway there.",
      "Everything you’ve ever wanted is on the other side of fear.",
      "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
      "Teach thy tongue to say, “I do not know,” and thous shalt progress.",
      "Start where you are. Use what you have.  Do what you can.",
      "When I was 5 years old, my mother always told me that happiness was the key to life.  When I went to school, they asked me what I wanted to be when I grew up.  I wrote down ‘happy’.  They told me I didn’t understand the assignment, and I told them they didn’t understand life.",
      "Fall seven times and stand up eight.",
      "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.",
      "Everything has beauty, but not everyone can see.",
      "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
      "When I let go of what I am, I become what I might be.",
      "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
      "Happiness is not something readymade.  It comes from your own actions.",
      "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.",
      "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.",
      "If the wind will not serve, take to the oars.",
      "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground.",
      "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.",
      "Too many of us are not living our dreams because we are living our fears.",
      "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
      "If you want to lift yourself up, lift up someone else.",
      "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.",
      "Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless.",
      "You take your life in your own hands, and what happens? A terrible thing, no one to blame.",
      "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.",
      "I didn’t fail the test. I just found 100 ways to do it wrong.",
      "In order to succeed, your desire for success should be greater than your fear of failure.",
      "A person who never made a mistake never tried anything new.",
      "The person who says it cannot be done should not interrupt the person who is doing it.",
      "There are no traffic jams along the extra mile.",
      "It is never too late to be what you might have been.",
      "You become what you believe.",
      "I would rather die of passion than of boredom.",
      "A truly rich man is one whose children run into his arms when his hands are empty.",
      "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
      "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
      "Build your own dreams, or someone else will hire you to build theirs.",
      "The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at.",
      "Education costs money.  But then so does ignorance.",
      "I have learned over the years that when one’s mind is made up, this diminishes fear.",
      "It does not matter how slowly you go as long as you do not stop.",
      "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.",
      "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
      "You can’t use up creativity.  The more you use, the more you have.",
      "Dream big and dare to fail.",
      "Our lives begin to end the day we become silent about things that matter.",
      "Do what you can, where you are, with what you have.",
      "If you do what you’ve always done, you’ll get what you’ve always gotten.",
      "Dreaming, after all, is a form of planning.",
      "It’s your place in the world; it’s your life. Go on and do all you can with it, and make it the life you want to live.",
      "You may be disappointed if you fail, but you are doomed if you don’t try.",
      "Remember no one can make you feel inferior without your consent.",
      "Life is what we make it, always has been, always will be.",
      "The question isn’t who is going to let me; it’s who is going to stop me.",
      "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
      "It’s not the years in your life that count. It’s the life in your years.",
      "Change your thoughts and you change your world.",
      "Either write something worth reading or do something worth writing.",
      "Nothing is impossible, the word itself says, “I’m possible!”",
      "The only way to do great work is to love what you do.",
      "If you can dream it, you can achieve it."
  ]

  
let wife  = [
      "Aww, my lovely wife! I hope you’ll forgive me for my mistakes. My apologies for my error.",
      "If you do not forgive me today, I’m strapped for time. So, I beg, dear!",
      "Your reasons for snubbing me are valid, and I have no objections, but please give me another chance.",
      "Every moment is painful for me if you are not satisfied.",
      "Love requires giving up. I admit my blunder. So, please relax now. You’re loved.",
      "How can I accidentally break your heart? And I never had any intention to make you cry. Please forgive me!",
      "I promise to be the husband of your dreams. I swear I’ll never hurt you again.",
      "Give me another chance, and I promise to improve.",
      "Give me a chance to fix everything I messed up. Help me, dear.",
      "Sweetheart! I’m sorry for hurting you. I didn’t mean to hurt you. I beg your pardon!",
      "Babe! I hope you’ll excuse my behavior last night. Please pardon my harmful actions.",
      "We fought for nothing. I’m sorry, sweetie. I promise it won’t happen again.",
      "I will always love and respect you. Don’t be upset by my delusions.",
      "We can’t avoid all surprises in our daily lives. Sorry for everything, sweetheart.",
      "Tolerance is one of my major flaws, and you know it. Please don’t be angry with me.",
      "You may not be able to feel my true regrets, but you may sense my heart’s sorrow. My favorite, I love you.",
      "I didn’t mean to, baby. I sincerely regret it. Forgive me, please, dear.  I’m sorry!",
      "You don’t deserve rudeness, and I feel like a bad husband for it. Please pardon me!",
      "Sorry for the pain, baby. I am worthless without your love.",
      "Please forgive me and love me again as I acknowledge my guilt.",
      "I regret that ignoring the incident would not have hurt you so much. I’m sorry, darling.",
      "Would you please stop prolonging our disagreement over that simple matter? Please pardon me.",
      "You may punish or pardon me, darling. But I apologize for the mishap.",
      "If you don’t forgive me, I’ll never be forgiven.",
      "Today I promise to turn every drop of your tears into a precious pearl. I’m sorry",
      "Lies are lies, no matter how small—shame on me for making you cry.",
      "Sweetheart, I am more to blame. My apologies.",
      "After that night, my mornings and nights are never the same. Sorry!",
      "I ask for forgiveness so we can be happy again. My dear, I adore you!",
      "I’m so sorry, (wife’s name). Let me make amends. ",
      "I adore you and always will. I am sorry for hurting you yesterday and seek an apology.",
      "I’m not sure where to start, but I want my wife to know I’m sorry for everything.",
      "Sweetheart! This message conveys my love and affection for you. I’m sorry!",
      "I was incapacitated, beloved. Everything just happened by chance. So forget it and forgive me.",
      "I don’t know what happened. So please excuse my errors.",
      "We both suffer when we fight over trivial matters. Please stop it!",
      "Thank you for being my wife and my mentor. Please pardon me.",
      "Please forgive my snobbery last night and help me grow up.",
      "I’m so sad I’ve upset you with my bad behavior. I’m sorry, sweetie.",
      "Please give me a second chance to improve. Please forgive me.",
      "I apologize for making you cry. If I haven’t been the man, I promised you.",
      "Sorry is a small word for my big error. But I can’t stand separation. I apologize!",
      "That’s why I’m asking for your forgiveness. I adore you.",
      "I can’t feel regret or remorse because the guilt of breaking your heart makes me numb. I’m sorry",
      "Dear! I never meant to hurt you. Give me one more chance, baby!",
      "I pledge to be your true man. Sorry, sweetheart; I will do my best to keep my promise.",
      "You chose me as your husband despite my inadequacy for your love. I apologize, honey.",
      "I realized that loving you includes accepting who you are and supporting your passions.",
      "Please return to our house. I promise we will get along better.",
      "Please accept my genuine apologies. Pardon me, honey.",
      "I’d do it for you. I’m sorry I hurt you, my beloved wife.",
      "Wrap yourself in its warmth and let my heart soften as I make amends. Excuse me!",
      "My lovely wife, Please accept my apology and allow me to repair our relationship.",
      "My wife, I am sorry I have hurt you so much.",
      "I am sorry we fought. I promise it wasn’t my intention. Sorry I made you sad. Sincere apologies, honey!",
      "I apologize for my deception. But I am not faking my sorry. Sorry, sweetheart.",
      "I haven’t eaten, slept, or shaved. I’ll be like this until my wife forgives me.",
      "I won’t let a few fights tarnish our love’s innocence. I promise not to lie again.",
      "I understand your anger. I’m sorry, honey.",
      "Please allow me to prove I am a better husband. I apologize.",
      "Because I am human, I made a mistake. But I want you to feel at home with me.",
      "I have loved you with all my heart and will continue to do so. I apologize for being rude.",
      "And I’ll never forgive myself for what I did. I’m sorry!",
      "I give up wheeling and dealing because we don’t deserve it, and I don’t want you upset alone.",
      "My life stops when you get grief from me and go silent. So, please give me another chance.",
      "I’m sorry you’re sad about all the memories and smiles we’ve shared. I’m so sorry.",
      "Lies are lies, no matter how small. I am sorry I made you cry. Give me a chance. I want to see the man I am in your smiles. I swear to be him.",
      "I never intended to be so cold. Excuse me, please.",
      "I have unknowingly hurt your feelings. Please excuse my lack of effort.",
      "I’m sorry I’ll be ready for your call. I adore you.",
      "I know I was wrong for claiming that I was right. Please accept my apologies.",
      "Every time I remember that I hurt you, I feel guilt hanging over me. Please forgive me.",
      "I am genuinely penitent, dear. Let me suffer the guilt of my wrongs.",
      "I never meant to hurt you. I don’t know what happened to me at that time. Please forgive me.",
      "I promise never to do this again. Please forgive me.",
      "I won’t let my attitude destroy our relationship. Forgive me, my sunshine.",
      "I will do anything and everything to make you smile again.",
      "Let me fix everything for the last time. I’m sorry, my love!",
      "My heart hurts without you. Please forgive me and let me be in your heart once again.",
      "That time, I lost control and said many bad words. But now I’m very sorry about that. Please forgive me, my love!",
      "I try just because I should. I am sorry. Please forgive me.",
      "I’m very sorry for being so rude and hurting you. Forgive me, sweetheart.",
      "Darling, I’m not too proud to admit that I was wrong. I’m so sorry.",
      "My dear wife, I am incredibly sorry for whatever I said. ",
      "Dear, during the goodbye time, I want to share some tips with you. ",
      "The faint flicker of hope that you can forgive me is all that keeps me alive.",
      "I am so sorry for making you question your choices. Take my hand, and let’s walk side by side again.",
      "I sink a little deeper into a pit of despair. I need the strength that your companionship offers.",
      "I am to rise to your understanding. I am sorry for letting you down.",
      "Please accept my apology and let us heal together.",
      "I have failed. Please give me a chance to try again, my sweetest wife.",
      "Now I woke up and felt like carrying the world on my shoulders. It’s because I hurt you. I’m sorry!",
      "I’m not perfect. Will you forgive me for making you suffer?",
      "A big part of my heart is broken for hurting you. I’m sorry for letting you down.",
      "I’m sorry! Can you give me a chance to make it up to you? I cannot see you like this.",
      "You mean more to me than anything in the world. Please forgive me, my darling wife.",
      "Why don’t you be the divine and beautiful goddess you are and forgive a mortal like me?",
      "It makes me weep as you are not talking to me. Please forgive me! I am sorry!",
      "Dear sweetheart! That time, I made a mistake. I’m incredibly sorry for that.",
      "Please give me a chance to repair what I damaged. I ask for your forgiveness, my dearest wife.",
      "You are my everything. How can I live well if you leave me so angrily?",
      "I became crazy and couldn’t tolerate anything. But I know you are kind enough to forgive me for anything wrong on my side. ",
      "You are my sweet wife, and I am your naughty husband. So you may have to pardon me frequently for my incivility.",
      "Believe me; I become more upset than you when I do anything wrong with you. ",
      "How can you leave my closeness when you know that whatever happens, I can’t live a moment without you?",
      "I acted in a state of unawareness. Now all I ask humbly, my queen, is for a chance to prove myself to you.",
      "Please forgive me, and I promise you will see the best of me in the time to come.",
      "To my sweet and lovely wife, with all the love, I say sorry, baby! Please forgive me, my love!",
      "The tears dropped from your eyes only to my devil side. Please accept my heartiest apology.",
      "I’m ashamed of who I’ve become more than what I did. I’m sorry."
];


export  {
      wife,
      motivation
};