
let quotes  = [
      "Aww, my lovely wife! I hope you’ll forgive me for my mistakes. My apologies for my error.",
      "If you do not forgive me today, I’m strapped for time. So, I beg, dear!",
      "Your reasons for snubbing me are valid, and I have no objections, but please give me another chance.",
      "Every moment is painful for me if you are not satisfied.",
      "Love requires giving up. I admit my blunder. So, please relax now. You’re loved.",
      "How can I accidentally break your heart? And I never had any intention to make you cry. Please forgive me!",
      "I promise to be the husband of your dreams. I swear I’ll never hurt you again.",
      "Give me another chance, and I promise to improve.",
      "Give me a chance to fix everything I messed up. Help me, dear.",
      "Sweetheart! I’m sorry for hurting you. I didn’t mean to hurt you. I beg your pardon!",
      "Babe! I hope you’ll excuse my behavior last night. Please pardon my harmful actions.",
      "We fought for nothing. I’m sorry, sweetie. I promise it won’t happen again.",
      "I will always love and respect you. Don’t be upset by my delusions.",
      "We can’t avoid all surprises in our daily lives. Sorry for everything, sweetheart.",
      "Tolerance is one of my major flaws, and you know it. Please don’t be angry with me.",
      "You may not be able to feel my true regrets, but you may sense my heart’s sorrow. My favorite, I love you.",
      "I didn’t mean to, baby. I sincerely regret it. Forgive me, please, dear.  I’m sorry!",
      "You don’t deserve rudeness, and I feel like a bad husband for it. Please pardon me!",
      "Sorry for the pain, baby. I am worthless without your love.",
      "Please forgive me and love me again as I acknowledge my guilt.",
      "I regret that ignoring the incident would not have hurt you so much. I’m sorry, darling.",
      "Would you please stop prolonging our disagreement over that simple matter? Please pardon me.",
      "You may punish or pardon me, darling. But I apologize for the mishap.",
      "If you don’t forgive me, I’ll never be forgiven.",
      "Today I promise to turn every drop of your tears into a precious pearl. I’m sorry",
      "Lies are lies, no matter how small—shame on me for making you cry.",
      "Sweetheart, I am more to blame. My apologies.",
      "After that night, my mornings and nights are never the same. Sorry!",
      "I ask for forgiveness so we can be happy again. My dear, I adore you!",
      "I’m so sorry, (wife’s name). Let me make amends. ",
      "I adore you and always will. I am sorry for hurting you yesterday and seek an apology.",
      "I’m not sure where to start, but I want my wife to know I’m sorry for everything.",
      "Sweetheart! This message conveys my love and affection for you. I’m sorry!",
      "I was incapacitated, beloved. Everything just happened by chance. So forget it and forgive me.",
      "I don’t know what happened. So please excuse my errors.",
      "We both suffer when we fight over trivial matters. Please stop it!",
      "Thank you for being my wife and my mentor. Please pardon me.",
      "Please forgive my snobbery last night and help me grow up.",
      "I’m so sad I’ve upset you with my bad behavior. I’m sorry, sweetie.",
      "Please give me a second chance to improve. Please forgive me.",
      "I apologize for making you cry. If I haven’t been the man, I promised you.",
      "Sorry is a small word for my big error. But I can’t stand separation. I apologize!",
      "That’s why I’m asking for your forgiveness. I adore you.",
      "I can’t feel regret or remorse because the guilt of breaking your heart makes me numb. I’m sorry",
      "Dear! I never meant to hurt you. Give me one more chance, baby!",
      "I pledge to be your true man. Sorry, sweetheart; I will do my best to keep my promise.",
      "You chose me as your husband despite my inadequacy for your love. I apologize, honey.",
      "I realized that loving you includes accepting who you are and supporting your passions.",
      "Please return to our house. I promise we will get along better.",
      "Please accept my genuine apologies. Pardon me, honey.",
      "I’d do it for you. I’m sorry I hurt you, my beloved wife.",
      "Wrap yourself in its warmth and let my heart soften as I make amends. Excuse me!",
      "My lovely wife, Please accept my apology and allow me to repair our relationship.",
      "My wife, I am sorry I have hurt you so much.",
      "I am sorry we fought. I promise it wasn’t my intention. Sorry I made you sad. Sincere apologies, honey!",
      "I apologize for my deception. But I am not faking my sorry. Sorry, sweetheart.",
      "I haven’t eaten, slept, or shaved. I’ll be like this until my wife forgives me.",
      "I won’t let a few fights tarnish our love’s innocence. I promise not to lie again.",
      "I understand your anger. I’m sorry, honey.",
      "Please allow me to prove I am a better husband. I apologize.",
      "Because I am human, I made a mistake. But I want you to feel at home with me.",
      "I have loved you with all my heart and will continue to do so. I apologize for being rude.",
      "And I’ll never forgive myself for what I did. I’m sorry!",
      "I give up wheeling and dealing because we don’t deserve it, and I don’t want you upset alone.",
      "My life stops when you get grief from me and go silent. So, please give me another chance.",
      "I’m sorry you’re sad about all the memories and smiles we’ve shared. I’m so sorry.",
      "Lies are lies, no matter how small. I am sorry I made you cry. Give me a chance. I want to see the man I am in your smiles. I swear to be him.",
      "I never intended to be so cold. Excuse me, please.",
      "I have unknowingly hurt your feelings. Please excuse my lack of effort.",
      "I’m sorry I’ll be ready for your call. I adore you.",
      "I know I was wrong for claiming that I was right. Please accept my apologies.",
      "Every time I remember that I hurt you, I feel guilt hanging over me. Please forgive me.",
      "I am genuinely penitent, dear. Let me suffer the guilt of my wrongs.",
      "I never meant to hurt you. I don’t know what happened to me at that time. Please forgive me.",
      "I promise never to do this again. Please forgive me.",
      "I won’t let my attitude destroy our relationship. Forgive me, my sunshine.",
      "I will do anything and everything to make you smile again.",
      "Let me fix everything for the last time. I’m sorry, my love!",
      "My heart hurts without you. Please forgive me and let me be in your heart once again.",
      "That time, I lost control and said many bad words. But now I’m very sorry about that. Please forgive me, my love!",
      "I try just because I should. I am sorry. Please forgive me.",
      "I’m very sorry for being so rude and hurting you. Forgive me, sweetheart.",
      "Darling, I’m not too proud to admit that I was wrong. I’m so sorry.",
      "My dear wife, I am incredibly sorry for whatever I said. ",
      "Dear, during the goodbye time, I want to share some tips with you. ",
      "The faint flicker of hope that you can forgive me is all that keeps me alive.",
      "I am so sorry for making you question your choices. Take my hand, and let’s walk side by side again.",
      "I sink a little deeper into a pit of despair. I need the strength that your companionship offers.",
      "I am to rise to your understanding. I am sorry for letting you down.",
      "Please accept my apology and let us heal together.",
      "I have failed. Please give me a chance to try again, my sweetest wife.",
      "Now I woke up and felt like carrying the world on my shoulders. It’s because I hurt you. I’m sorry!",
      "I’m not perfect. Will you forgive me for making you suffer?",
      "A big part of my heart is broken for hurting you. I’m sorry for letting you down.",
      "I’m sorry! Can you give me a chance to make it up to you? I cannot see you like this.",
      "You mean more to me than anything in the world. Please forgive me, my darling wife.",
      "Why don’t you be the divine and beautiful goddess you are and forgive a mortal like me?",
      "It makes me weep as you are not talking to me. Please forgive me! I am sorry!",
      "Dear sweetheart! That time, I made a mistake. I’m incredibly sorry for that.",
      "Please give me a chance to repair what I damaged. I ask for your forgiveness, my dearest wife.",
      "You are my everything. How can I live well if you leave me so angrily?",
      "I became crazy and couldn’t tolerate anything. But I know you are kind enough to forgive me for anything wrong on my side. ",
      "You are my sweet wife, and I am your naughty husband. So you may have to pardon me frequently for my incivility.",
      "Believe me; I become more upset than you when I do anything wrong with you. ",
      "How can you leave my closeness when you know that whatever happens, I can’t live a moment without you?",
      "I acted in a state of unawareness. Now all I ask humbly, my queen, is for a chance to prove myself to you.",
      "Please forgive me, and I promise you will see the best of me in the time to come.",
      "To my sweet and lovely wife, with all the love, I say sorry, baby! Please forgive me, my love!",
      "The tears dropped from your eyes only to my devil side. Please accept my heartiest apology.",
      "I’m ashamed of who I’ve become more than what I did. I’m sorry."
];


export default quotes;